language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: fwrpA/fpgkkQgf7v270zYdD+1qttOrX0r/oYczhz1WZe04cYiMn8MDlNXruZ2erg6hV2MPyFhRMPjC+McpFJIdiiAguX0DLxMp7ugpczXnSvlBFYyHr29veDFuQ6lS+Xw3WAEqPf+87ssdGzVMTiGdiojhzj1W2bP4ncqE5UPHa81Fr6MsKVmu33qFHij+1WbZw1UpS9HWJ+YA+r83U7JFx5eMqVRu2v7vlB4/gqL1S7j/TA1eruTRszQ+1d6xHGusrAN/jaWkZO9Dq67e8uMW4awWJhYLcaQC8HVnjhy+kj20h1QiAsQEyfZ6OgTsTnOgRkrYgTlCDpzKjLJnmwnrhZo5GFRbZchyNu02SkA3jYXU5VpieeFxnhdKW3Z47FM9LXVPbwt97gRbzOQtu2IGx28HbQ1V5TOlCq6cW8phxB411O6LjE2Tpj4L2WkcPRvJo/XyUtP4PBcyfokUFAXuVPTj4yk+vlEPPim4StCdqjGotkh8xwmGdUrxGzuQ1vcEl9hBvnn+1nkX+35MxTm5w7rjzUMNlNgnE4Bt29hTbiLf7zoC6hVBOl8nQe75WeFHadDkuAHkuNj9q3men6Hd9r3Mbwky+zfIBP2zQfsTlGYoft4AwjDRMjPsI5kaZlKmsIKTEv6GDQatQTYMGkPQo22v4bgIEAyylZDB3vbxc=
  app: reactreduxwebshop
  on:
    repo: dinespoulsen/reactReduxWebshop
