language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: a/Ka8JhA+6p7pHMZqzU5eDlm+JZijhq35ORFPaeDJWyI3q7wuhnDeKN0jS+Gfry0nU2pxFt4TEZQEpq/vMdKz66/SWpNRylMd9AkNFf9xN2FIdpNw3YZzqZ7/aDWPO414YxL8ugPL+Xf1thbY5tjp+MQ65cllbbRI2NRVblVoCfEwZHQQ7QYmX1f+vnv6vRuYJnEDnSLb0BaShUZUFdRmFu9p8WcBV9EZzwOKldf1Bp2QqVP2QWrAdS2KNL003xGxzpJTRZ4z6+omjNlpjuiWnTYbxJcx201PDqU2eQ0C+/5QjyFLufFWZ2m1gNCppcLRUR8/d9KlJb3Elil4nGfdKGihVTmNy4okliW4hwkVIZsk/3ZP0o3j6cqBiq0JdP2RgrNeZYrfc0n8YK0xXRrOk4zG/uzlb6Smc4JkxOEDjy5cBy9slSeQXXfZ1vZTmj/y4pG4gVgDQO+ua/0mcV78MFMM7nJSr52MbcZRf01wjGPGZKLekI65I3hWFUstOibjJuPMXOSAMoA9xWXH67aleBf4QydhJhyPP1Lkwg1sLvkkp6iqajpX7Wvl5YhS1rNkfhgdtIjIU+wOARzkWBMbasIcNatd4x/IYdM1Bj964IjTRpfcTYDlTiWMMWZ0eN0g5JOMe/Xvlag4CzpqI/qsyHvBL98fKU4KhFntv7p2bY=
