language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: "KnPvahYkOI2wNzoWcQS4y2leuauVSsEWJa3Bnry+urjUx752QQrZdCApwhJMUHvTEIz7lz1pAuxlGdSRTWKVV9eXDrzuKEGgroyE5Rv0hHF96RduByWQmd8zk/6waBUQkFBT3gcJIzNWJ5Ftt7nXRGDPyvpiAAnyoQy8kIgW9Ue2ZGhVB58Pu1kXr1+OYfRv/1CygqggYblIxiQds6WVlnodHR5pVCaXkuedJdg7ec66T9Car01wRgDDXkHqI4y0oJl16Yk9TB49I7w+SMjsYIpH1hoy8MFEU71azc9on/AsmGrrVXr/1Q3rmCvfOXd/WUUn6GP1Y/mx9DTOXXzn3IQOTdxIg3zWMln4dh8BluzIu2KBzW2enziaVs0Eb0wwXxI//5ZJf2TXHL1RK/JdOlo8Nac4rRww/QLw7EKVsUmamXBEwqEOKP3Kl3JGxug+Iv2Sg3+/69Sv6L8kTuUhfuoOEg017NALVClRHpQWZnaAUtqgkB/mA7Tn47E6izNDBiYI4ImXLIdlCe9CcKnJQP6ZKKTPek044RlXt2nW6tDXQ6zCr/W82nVnJjRzGgxL9bdfZjwyGu8lxlDUzWz+jCox2NRO8ZXOQ8mPltWV7EX3QKH9HSrPqmy6Osf5313gFoNzGUNC8Y5t5Hn6Q2GKSgbRyYBGlTTzrH3/m3E//wc="
    strategy: git
